### ISSUE TITLE
Fatal Error (osmparser.c:449): Node ID too large

### ISSUE THREAD

**Issue by leo7r** [zbycz/routing-thesis#3]
I am getting this error when running `planetsplitter`:

```
Parse OSM Data [greater-london-latest.osm]
==============

Reading: Lines=4549861 Nodes=3330000 Ways=0 Relations=0Routino Fatal Error (osmparser.c:449): Node ID too large (change node_t to 64-bits?)
```

**Comment by leo7r** [comment]
The solution is the following:

1. Open `src/types.h`
2. Change `typedef uint32_t index_t;` for `typedef uint64_t index_t;`
3. Open `src/typesx.h`
4. Change `typedef uint32_t node_t;` for `typedef uint64_t node_t;`
5. Change `typedef uint32_t way_t;` for `typedef uint64_t way_t;`
6. Change `typedef uint32_t relation_t;` for `typedef uint64_t relation_t;`
7. Run `make` and everything should work just fine.

**Comment by zbycz** [comment]
Thanks for the solution. 
For newer repo see #1 or even code from routino.org
